name: CMake
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.generator }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          ubuntu-18.04,
          ubuntu-20.04,
          ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      # If your project use submodule, please uncomment the following line.
      # with:
      #   submodules: recursive
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1.4
      with:
        version: latest
        platform: x64

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TOOL=gcc

    - name: Build
      working-directory: ${{github.workspace}}/build
      # Build your program with the given configuration
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --output-on-failure --rerun-failed